"use strict";
/*Compiled using Cheerp (R) by Leaning Technologies Ltd*/
var __imul=Math.imul;
var __fround=Math.fround;
var oSlot=0;var nullArray=[null];var nullObj={d:nullArray,o:0};
function __ZN15BubbleContainer6doStepEv(Lthis){
	var Lsub37=-0.,Lfx=null,tmp2=null,tmp3=null,tmp3o=0,Li48$p038=0,Ladd$pi236=0,LmergedArray=null,LmergedArrayo=0,Lfy=null,Lcall4$ppeel=-0.,Lcall8$ppeel=-0.,Li$p050=0,Ladd$pi=0,Lcall8=-0.,Ladd$pi223=0,Lsub33=-0.,tmp15=null,tmp15o=0,tmp16=null;
	tmp3=Lthis.a1;
	Li48$p038=tmp3.i5|0;
	if((Li48$p038|0)!==0){
		Ladd$pi236=tmp3.i4|0;
		LmergedArrayo=tmp3.a1o;
		LmergedArray=tmp3.a1;
		Lfy=LmergedArray[LmergedArrayo+((Ladd$pi236>>>0)/124|0)|0];
		Lcall4$ppeel=+__ZNK6Bubble1xEv(+Lfy.d[Lfy.o+((Ladd$pi236>>>0)%124|0)|0].d0);
		Lcall8$ppeel=+__ZNK6Bubble1yEv(+Lfy.d[Lfy.o+((Ladd$pi236>>>0)%124|0)|0].a1[0]);
		Lcall4$ppeel=+_fmin(+_fmin(+_fmin(+_fmin(.5,Lcall4$ppeel),1-Lcall4$ppeel),Lcall8$ppeel),1-Lcall8$ppeel);
		if((Li48$p038|0)!==1){
			Li$p050=1;
			while(1){
				Ladd$pi=Ladd$pi236+Li$p050|0;
				Lfy=LmergedArray[LmergedArrayo+((Ladd$pi>>>0)/124|0)|0];
				Lcall8$ppeel=+__ZNK6Bubble1xEv(+Lfy.d[Lfy.o+((Ladd$pi>>>0)%124|0)|0].d0);
				Lcall8=+__ZNK6Bubble1yEv(+Lfy.d[Lfy.o+((Ladd$pi>>>0)%124|0)|0].a1[0]);
				Lcall4$ppeel=+_fmin(+_fmin(+_fmin(+_fmin(Lcall4$ppeel,Lcall8$ppeel),1-Lcall8$ppeel),Lcall8),1-Lcall8);
				Li$p050=Li$p050+1|0;
				if(Li$p050>>>0<Li48$p038>>>0)continue;
				break;
			}
		}
		Lcall4$ppeel+=.01;
		Ladd$pi236=tmp3.i4|0;
		tmp3o=tmp3.a1o;
		tmp3=tmp3.a1;
		Lcall4$ppeel*=(Lcall4$ppeel*4);
		Li$p050=0;
		while(1){
			Ladd$pi=Ladd$pi236+Li$p050|0;
			LmergedArray=tmp3[tmp3o+((Ladd$pi>>>0)/124|0)|0];
			Li$p050=Li$p050+1|0;
			if(Li$p050>>>0<Li48$p038>>>0){
				Lcall8$ppeel=+__ZNK6Bubble1xEv(+LmergedArray.d[LmergedArray.o+((Ladd$pi>>>0)%124|0)|0].d0);
				Lcall8=+__ZNK6Bubble1yEv(+LmergedArray.d[LmergedArray.o+((Ladd$pi>>>0)%124|0)|0].a1[0]);
				Ladd$pi=Li$p050;
				while(1){
					Ladd$pi223=Ladd$pi+Ladd$pi236|0;
					LmergedArray=tmp3[tmp3o+((Ladd$pi223>>>0)/124|0)|0];
					Lsub33= +__ZNK6Bubble1xEv(+LmergedArray.d[LmergedArray.o+((Ladd$pi223>>>0)%124|0)|0].d0)-Lcall8$ppeel;
					Lsub37= +__ZNK6Bubble1yEv(+LmergedArray.d[LmergedArray.o+((Ladd$pi223>>>0)%124|0)|0].a1[0])-Lcall8;
					Lcall4$ppeel=+_fmin(Lcall4$ppeel,Lsub33*Lsub33+Lsub37*Lsub37);
					Ladd$pi=Ladd$pi+1|0;
					if((Ladd$pi|0)!==(Li48$p038|0))continue;
					break;
				}
			}
			if((Li$p050|0)!==(Li48$p038|0))continue;
			break;
		}
	}else{
		Lcall4$ppeel=1.0404;
	}
	Lcall4$ppeel=+Math.sqrt(Lcall4$ppeel);
	tmp3=Lthis.a1;
	Lcall4$ppeel*=.5;
	if((tmp3.i5|0)!==0){
		LmergedArray=tmp3;
		Li48$p038=0;
		while(1){
			Ladd$pi236=(LmergedArray.i4|0)+Li48$p038|0;
			tmp3o=tmp3.a1o;
			tmp3=tmp3.a1;
			tmp3=tmp3[tmp3o+((Ladd$pi236>>>0)/124|0)|0];
			__ZN6Bubble12changeRadiusEd(tmp3.d[tmp3.o+((Ladd$pi236>>>0)%124|0)|0],Lcall4$ppeel);
			tmp3=Lthis.a1;
			Li48$p038=Li48$p038+1|0;
			if(Li48$p038>>>0<tmp3.i5>>>0){
				LmergedArray=tmp3;
				continue;
			}
			break;
		}
	}
	LmergedArray=[-0.,-0.];
	Lfy={a0:nullArray,a1:nullArray,a1o:0,a2:{a0:null}};
	Lfx={a0:nullArray,a1:nullArray,a1o:0,a2:{a0:null}};
	Li48$p038=0;
	while(1){
		Ladd$pi236=tmp3.i5|0;
		LmergedArray[1]=0;
		__ZNSt6vectorIdSaIdEEC2EjRKd(Lfx,Ladd$pi236,LmergedArray,1);
		Ladd$pi236=Lthis.a1.i5|0;
		LmergedArray[0]=0;
		__ZNSt6vectorIdSaIdEEC2EjRKd(Lfy,Ladd$pi236,LmergedArray,0);
		tmp15=Lthis.a1;
		if((tmp15.i5|0)!==0){
			tmp3=tmp15;
			Ladd$pi236=0;
			while(1){
				Li$p050=(tmp3.i4|0)+Ladd$pi236|0;
				tmp3o=tmp15.a1o;
				tmp3=tmp15.a1;
				tmp16=tmp3[tmp3o+((Li$p050>>>0)/124|0)|0];
				tmp3=tmp15;
				Ladd$pi=0;
				while(1){
					if((Ladd$pi|0)!==(Ladd$pi236|0)){
						Ladd$pi223=(tmp3.i4|0)+Ladd$pi|0;
						tmp3o=tmp15.a1o;
						tmp3=tmp15.a1;
						tmp3=tmp3[tmp3o+((Ladd$pi223>>>0)/124|0)|0];
						Lcall8$ppeel= +__ZNK6Bubble1xEv(+tmp3.d[tmp3.o+((Ladd$pi223>>>0)%124|0)|0].d0)- +__ZNK6Bubble1xEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].d0);
						Lcall8= +__ZNK6Bubble1yEv(+tmp3.d[tmp3.o+((Ladd$pi223>>>0)%124|0)|0].a1[0])- +__ZNK6Bubble1yEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].a1[0]);
						Lcall8$ppeel=Lcall8$ppeel*Lcall8$ppeel+Lcall8*Lcall8;
						Lcall8=+Math.sqrt(Lcall8$ppeel);
						Lcall8$ppeel=1/Lcall8$ppeel;
						tmp15=Lfx.a0;
						tmp15[Ladd$pi]=Lcall8$ppeel*( +__ZNK6Bubble1xEv(+tmp3.d[tmp3.o+((Ladd$pi223>>>0)%124|0)|0].d0)- +__ZNK6Bubble1xEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].d0))/Lcall8+ +tmp15[Ladd$pi];
						tmp15=Lfy.a0;
						tmp15[Ladd$pi]=Lcall8$ppeel*( +__ZNK6Bubble1yEv(+tmp3.d[tmp3.o+((Ladd$pi223>>>0)%124|0)|0].a1[0])- +__ZNK6Bubble1yEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].a1[0]))/Lcall8+ +tmp15[Ladd$pi];
						tmp15=Lthis.a1;
					}
					Ladd$pi223=tmp15.i5|0;
					Ladd$pi=Ladd$pi+1|0;
					if(Ladd$pi>>>0<Ladd$pi223>>>0){
						tmp3=tmp15;
						continue;
					}
					break;
				}
				Lcall8$ppeel=+__ZNK6Bubble1xEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].d0);
				Lcall8=(+(Ladd$pi223>>>0));
				if(Lcall8$ppeel>0){
					tmp3=Lfx.a0;
					Lcall8$ppeel=Lcall8/Lcall8$ppeel+ +tmp3[Ladd$pi236];
					tmp3[Ladd$pi236]=Lcall8$ppeel;
				}else{
					tmp3=Lfx.a0;
					Lcall8$ppeel=Lcall8*2/Lcall4$ppeel+ +tmp3[Ladd$pi236];
					tmp3[Ladd$pi236]=Lcall8$ppeel;
				}
				Lsub33=+__ZNK6Bubble1xEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].d0);
				if(Lsub33<1)tmp3[Ladd$pi236]=Lcall8$ppeel-Lcall8/(1-Lsub33);
				else tmp3[Ladd$pi236]=Lcall8$ppeel-Lcall8*2/Lcall4$ppeel;
				Lcall8$ppeel=+__ZNK6Bubble1yEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].a1[0]);
				if(Lcall8$ppeel>0){
					tmp3=Lfy.a0;
					Lcall8$ppeel=Lcall8/Lcall8$ppeel+ +tmp3[Ladd$pi236];
					tmp3[Ladd$pi236]=Lcall8$ppeel;
				}else{
					tmp3=Lfy.a0;
					Lcall8$ppeel=Lcall8*2/Lcall4$ppeel+ +tmp3[Ladd$pi236];
					tmp3[Ladd$pi236]=Lcall8$ppeel;
				}
				Lsub33=+__ZNK6Bubble1yEv(+tmp16.d[tmp16.o+((Li$p050>>>0)%124|0)|0].a1[0]);
				if(Lsub33<1)tmp3[Ladd$pi236]=Lcall8$ppeel-Lcall8/(1-Lsub33);
				else tmp3[Ladd$pi236]=Lcall8$ppeel-Lcall8*2/Lcall4$ppeel;
				tmp15=Lthis.a1;
				Li$p050=tmp15.i5|0;
				Ladd$pi236=Ladd$pi236+1|0;
				if(Ladd$pi236>>>0<Li$p050>>>0){
					tmp3=tmp15;
					continue;
				}
				if((Li$p050|0)!==0){
					tmp3=Lfx.a0;
					tmp16=Lfy.a0;
					tmp2=tmp15;
					Ladd$pi236=0;
					while(1){
						Li$p050=(tmp2.i4|0)+Ladd$pi236|0;
						tmp15o=tmp15.a1o;
						tmp15=tmp15.a1;
						tmp15=tmp15[tmp15o+((Li$p050>>>0)/124|0)|0];
						tmp15.d[tmp15.o+((Li$p050>>>0)%124|0)|0].d0= +tmp3[Ladd$pi236]/1.0E+5+ +tmp15.d[tmp15.o+((Li$p050>>>0)%124|0)|0].d0;
						tmp15.d[tmp15.o+((Li$p050>>>0)%124|0)|0].a1[0]= +tmp16[Ladd$pi236]/1.0E+5+ +tmp15.d[tmp15.o+((Li$p050>>>0)%124|0)|0].a1[0];
						tmp15=Lthis.a1;
						Ladd$pi236=Ladd$pi236+1|0;
						if(Ladd$pi236>>>0<tmp15.i5>>>0){
							tmp2=tmp15;
							continue;
						}
						break;
					}
				}
				break;
			}
		}
		__ZNSt6vectorIdSaIdEED2Ev(Lfy);
		__ZNSt6vectorIdSaIdEED2Ev(Lfx);
		Li48$p038=Li48$p038+1|0;
		if((Li48$p038|0)===20){
			__ZN15BubbleContainer14recalculateAllEv(Lthis);
			return;
		}
		tmp3=Lthis.a1;
		continue;
	}
}
function __ZN15BubbleContainer14recalculateAllEv(Lthis){
	var Ladd$pi=0,tmp1=null,tmp2=null,tmp2o=0,Li$p03=0;
	tmp1=Lthis.a1;
	if((tmp1.i5|0)!==0){
		tmp2=tmp1;
		Li$p03=0;
		while(1){
			Ladd$pi=(tmp2.i4|0)+Li$p03|0;
			tmp2o=tmp1.a1o;
			tmp2=tmp1.a1;
			tmp2=tmp2[tmp2o+((Ladd$pi>>>0)/124|0)|0];
			__ZN6Bubble11setPositionEv(tmp2.d[tmp2.o+((Ladd$pi>>>0)%124|0)|0]);
			tmp1=Lthis.a1;
			Li$p03=Li$p03+1|0;
			if(Li$p03>>>0<tmp1.i5>>>0){
				tmp2=tmp1;
				continue;
			}
			break;
		}
	}
}
function __ZN6Bubble11setPositionEv(Lthis){
	var Lcall=null,LretConstructor=null;
	Lcall=Lthis.a3.style;
	LretConstructor=String(( +__ZNK6Bubble1xEv(+Lthis.d0)- +Lthis.a5[0])*100);
	Lcall.left=LretConstructor.concat("%");
	Lcall=Lthis.a3.style;
	LretConstructor=String(( +__ZNK6Bubble1yEv(+Lthis.a1[0])- +Lthis.a5[0])*100);
	Lcall.top=LretConstructor.concat("%");
	Lcall=Lthis.a3.style;
	LretConstructor=String( +Lthis.a5[0]*2*100);
	Lcall.width=LretConstructor.concat("%");
	Lcall=Lthis.a3.style;
	LretConstructor=String( +Lthis.a5[0]*2*100);
	Lcall.height=LretConstructor.concat("%");
}
function _cheerpCreate_ZN6client6StringC2EPKc(Larg0,Marg0){
	return String(__ZN6client6String11fromCharPtrIcEEPS0_PKT_(Larg0,Marg0));
}
function __ZN6client6String11fromCharPtrIcEEPS0_PKT_(Ls,Ms){
	var LretConstructor=null,tmp1=0,Lgeptoindexphi=0;
	LretConstructor=String();
	tmp1=Ls[Ms]|0;
	if((tmp1&255)===0)return LretConstructor;
	Lgeptoindexphi=0;
	while(1){
		LretConstructor=LretConstructor.concat(String.fromCharCode(tmp1<<24>>24));
		Lgeptoindexphi=Lgeptoindexphi+1|0;
		tmp1=Ls[Ms+Lgeptoindexphi|0]|0;
		if((tmp1&255)!==0)continue;
		break;
	}
	return LretConstructor;
}
function __ZNSt6vectorIdSaIdEED2Ev(Lthis){
	__ZNSt13__vector_baseIdSaIdEED2Ev(Lthis);
}
function __ZNSt13__vector_baseIdSaIdEED2Ev(Lthis){
	var tmp0=null,tmp1=null,tmp1o=0;
	tmp0=Lthis.a0;
	if(tmp0!==nullArray||0!==0){
		tmp1o=Lthis.a1o;
		tmp1=Lthis.a1;
		if(tmp0!==tmp1||0!==tmp1o){
			Lthis.a1=tmp1;
			Lthis.a1o=tmp1o+(((Math.imul(tmp1o,8))-(Math.imul(0,8))|0)-8>>>3^ -1)|0;
		}
	}
}
function __ZNSt6vectorIdSaIdEEC2EjRKd(Lthis,L__n,L__x,M__x){
	var L$ppre=null,L$ppreo=0,L__n$paddr$p0$pi=0;
	Lthis.a0=nullArray;
	Lthis.a1=nullArray;
	Lthis.a1o=0;
	Lthis.a2.a0=null;
	if((L__n|0)!==0){
		__ZNSt6vectorIdSaIdEE8allocateEj(Lthis,L__n);
		L$ppreo=Lthis.a1o;
		L$ppre=Lthis.a1;
		L__n$paddr$p0$pi=L__n;
		while(1){
			L$ppre[L$ppreo]=+L__x[M__x];
			L$ppreo=Lthis.a1o;
			L$ppre=Lthis.a1;
			Lthis.a1=L$ppre;
			Lthis.a1o=L$ppreo+1|0;
			L__n$paddr$p0$pi=L__n$paddr$p0$pi-1|0;
			if((L__n$paddr$p0$pi|0)!==0){
				L$ppreo=L$ppreo+1|0;
				L$ppre=L$ppre;
				continue;
			}
			break;
		}
	}
}
function __ZNSt6vectorIdSaIdEE8allocateEj(Lthis,L__n){
	var tmp0=null;
	tmp0=createArray_literal1((L__n<<3)/8|0);
	Lthis.a1=tmp0;
	Lthis.a1o=0;
	Lthis.a0=tmp0;
	Lthis.a2.a0=tmp0[L__n];
}
function __ZN6Bubble12changeRadiusEd(Lthis,LnewRadius){
	var L$psroa$pspeculated=-0.,Lsub=-0.,Lcond$mlvalue$pi$pi37$psroa$pspeculated=-0.;
	L$psroa$pspeculated=LnewRadius<.5?LnewRadius:.5;
	Lthis.a5[0]=L$psroa$pspeculated;
	Lcond$mlvalue$pi$pi37$psroa$pspeculated=+Lthis.d0;
	if(Lcond$mlvalue$pi$pi37$psroa$pspeculated<L$psroa$pspeculated){
		Lcond$mlvalue$pi$pi37$psroa$pspeculated=L$psroa$pspeculated;
	}
	Lthis.d0=Lcond$mlvalue$pi$pi37$psroa$pspeculated;
	Lsub=1-L$psroa$pspeculated;
	if(Lsub<Lcond$mlvalue$pi$pi37$psroa$pspeculated){
		Lcond$mlvalue$pi$pi37$psroa$pspeculated=Lsub;
	}
	Lthis.d0=Lcond$mlvalue$pi$pi37$psroa$pspeculated;
	Lcond$mlvalue$pi$pi37$psroa$pspeculated=+( +Lthis.a1[0]<L$psroa$pspeculated?Lthis.a5:Lthis.a1)[ +Lthis.a1[0]<L$psroa$pspeculated?0:0];
	Lthis.a1[0]=Lcond$mlvalue$pi$pi37$psroa$pspeculated;
	if(Lsub<Lcond$mlvalue$pi$pi37$psroa$pspeculated){
		Lthis.a1[0]=Lsub;
		return;
	}
	Lthis.a1[0]=Lcond$mlvalue$pi$pi37$psroa$pspeculated;
}
function _fmin(Lx,Ly){
	if((___fpclassifyd(Lx)|0|0)!==0){
		if((___fpclassifyd(Ly)|0|0)!==0)return Lx<Ly?Lx:Ly;
		return Lx;
	}
	return Ly;
}
function ___fpclassifyd(Lx){
	var Lew_u=null,tmp1=0,tmp2=0;
	Lew_u={d:new DataView(new ArrayBuffer(8)),o:0};
	Lew_u.d.setFloat64(Lew_u.o,Lx,true);
	tmp1=Lew_u.d.getInt32(1*4+Lew_u.o,true)|0;
	tmp2=Lew_u.d.getInt32(Lew_u.o,true)|0;
	if((tmp2|tmp1|0)!==0){
		if((tmp1|0)===-2147483648)if((tmp2|0)===0)return 2|0;
		if((tmp1&2147483647)-1048576>>>0<2145386496)return 4|0;
		if(tmp1>>>0<1048576)return 3|0;
		if((tmp1|0)<0)if(tmp1>>>0<2148532224)return 3|0;
		if((tmp1|0)===2146435072)if((tmp2|0)===0)return 1|0;
		return ((tmp1|0)===-1048576&&(tmp2|0)===0?1:0)|0;
	}
	return 2|0;
}
function __ZNK6Bubble1yEv(Lthis$p0$p1$pval){
	return Lthis$p0$p1$pval;
}
function __ZNK6Bubble1xEv(Lthis$p0$p0$pval){
	return Lthis$p0$p0$pval;
}
function __ZN15BubbleContainer5eraseEPN6client11HTMLElementE(Lthis,Linner){
	var L__begin=null,tmp1=null,tmp1o=0,L$ppre$mphi=null,L$ppre$mphio=0,L__end=null,L__endo=0,Lsub$pi23=0,L__t$pi=null;
	L$ppre$mphi=Lthis.a1;
	if(L$ppre$mphi!==null){
		L$ppre$mphi=L$ppre$mphi;
	}else{
		L$ppre$mphi={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:L$ppre$mphi={a0:nullArray,a0o:0},i4:0,i5:0};
		L$ppre$mphi.a0=nullArray;
		L$ppre$mphi.a1=nullArray;
		L$ppre$mphi.a1o=0;
		L$ppre$mphi.a2=nullArray;
		L$ppre$mphi.a2o=0;
		L$ppre$mphi.a3.a0=nullArray;
		L$ppre$mphi.a3.a0o=0;
		L$ppre$mphi.i4=0;
		L$ppre$mphi.i5=0;
		Lthis.a1=L$ppre$mphi;
		L$ppre$mphi=L$ppre$mphi;
	}
	L__begin={a0:nullArray,a0o:0,a1:nullArray,a1o:0};
	__ZNSt12__deque_baseI6BubbleSaIS0_EE5beginEv(L__begin,L$ppre$mphi);
	L__end={a0:nullArray,a0o:0,a1:nullArray,a1o:0};
	__ZNSt12__deque_baseI6BubbleSaIS0_EE3endEv(L__end,L$ppre$mphi);
	L$ppre$mphio=L__begin.a1o;
	L$ppre$mphi=L__begin.a1;
	L__endo=L__end.a1o;
	L__end=L__end.a1;
	if(L$ppre$mphi!==L__end||L$ppre$mphio!==L__endo)while(1){
		if(L$ppre$mphi[L$ppre$mphio].a2===Linner){
			L__begin.a1=L$ppre$mphi;
			L__begin.a1o=L$ppre$mphio;
			L__end=Lthis.a1;
			Lsub$pi23=((L__end.i5|0)-1|0)+(L__end.i4|0)|0;
			L__endo=L__end.a1o;
			L__end=L__end.a1;
			L__end=L__end[L__endo+((Lsub$pi23>>>0)/124|0)|0];
			L__t$pi={d0:-0.,a1:[-0.],a2:null,a3:null,i4:0,a5:[-0.]};
			L__t$pi.d0=+L$ppre$mphi[L$ppre$mphio].d0;
			L__t$pi.a1[0]=+L$ppre$mphi[L$ppre$mphio].a1[0];
			L__t$pi.a2=L$ppre$mphi[L$ppre$mphio].a2;
			L__t$pi.a3=L$ppre$mphi[L$ppre$mphio].a3;
			L__t$pi.i4=L$ppre$mphi[L$ppre$mphio].i4|0;
			L__t$pi.a5[0]=+L$ppre$mphi[L$ppre$mphio].a5[0];
			L$ppre$mphi[L$ppre$mphio].d0=+L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].d0;
			L$ppre$mphi[L$ppre$mphio].a1[0]=+L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a1[0];
			L$ppre$mphi[L$ppre$mphio].a2=L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a2;
			L$ppre$mphi[L$ppre$mphio].a3=L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a3;
			L$ppre$mphi[L$ppre$mphio].i4=L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].i4|0;
			L$ppre$mphi[L$ppre$mphio].a5[0]=+L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a5[0];
			L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].d0=+L__t$pi.d0;
			L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a1[0]=+L__t$pi.a1[0];
			L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a2=L__t$pi.a2;
			L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a3=L__t$pi.a3;
			L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].i4=L__t$pi.i4|0;
			L__end.d[L__end.o+((Lsub$pi23>>>0)%124|0)|0].a5[0]=+L__t$pi.a5[0];
			L$ppre$mphi=Lthis.a1;
			Lsub$pi23=((L$ppre$mphi.i5|0)-1|0)+(L$ppre$mphi.i4|0)|0;
			L$ppre$mphio=L$ppre$mphi.a1o;
			L$ppre$mphi=L$ppre$mphi.a1;
			L$ppre$mphi=L$ppre$mphi[L$ppre$mphio+((Lsub$pi23>>>0)/124|0)|0];
			__ZN6Bubble9invisibleER15BubbleContainer(L$ppre$mphi.d[L$ppre$mphi.o+((Lsub$pi23>>>0)%124|0)|0],Lthis);
			__ZNSt5dequeI6BubbleSaIS0_EE8pop_backEv(Lthis.a1);
		}else{
			tmp1o=L__begin.a0o;
			tmp1=L__begin.a0;
			L__t$pi=tmp1[tmp1o];
			if(((Math.imul(L$ppre$mphio+1|0,33))-(Math.imul(L__t$pi.o,33))|0)===4092){
				L__begin.a0=tmp1;
				L__begin.a0o=tmp1o+1|0;
				L$ppre$mphi=tmp1[tmp1o+1|0];
				L$ppre$mphio=L$ppre$mphi.o;
				L$ppre$mphi=L$ppre$mphi.d;
			}else{
				L$ppre$mphio=L$ppre$mphio+1|0;
				L$ppre$mphi=L$ppre$mphi;
			}
			if(L$ppre$mphi!==L__end||L$ppre$mphio!==L__endo)continue;
			L__begin.a1=L__end;
			L__begin.a1o=L__endo;
		}
		break;
	}
}
function __ZNSt5dequeI6BubbleSaIS0_EE8pop_backEv(Lthis){
	var tmp0=0,tmp1=null,tmp1o=0,tmp2=null,tmp2o=0,Lsub$pptr$plhs$pcast$pi$pi$pi=0,Lsub$pptr$prhs$pcast$pi$pi$pi=0;
	tmp0=Lthis.i5|0;
	Lthis.i5=tmp0-1|0;
	tmp1o=Lthis.a2o;
	tmp1=Lthis.a2;
	tmp2o=Lthis.a1o;
	tmp2=Lthis.a1;
	Lsub$pptr$prhs$pcast$pi$pi$pi=(Math.imul(tmp2o,4));
	Lsub$pptr$plhs$pcast$pi$pi$pi=(Math.imul(tmp1o,4));
	if((Lsub$pptr$plhs$pcast$pi$pi$pi|0)===(Lsub$pptr$prhs$pcast$pi$pi$pi|0)){
		Lsub$pptr$prhs$pcast$pi$pi$pi=0;
	}else{
		Lsub$pptr$prhs$pcast$pi$pi$pi=(__imul(Lsub$pptr$plhs$pcast$pi$pi$pi-Lsub$pptr$prhs$pcast$pi$pi$pi>>2,124)|0)-1|0;
	}
	if((Lsub$pptr$prhs$pcast$pi$pi$pi+(1-tmp0|0)|0)-(Lthis.i4|0)>>>0>247){
		Lthis.a2=tmp1;
		Lthis.a2o=tmp1o+ -1|0;
	}
}
function __ZN6Bubble9invisibleER15BubbleContainer(Lthis,LbubbleContainer){
	Lthis.i4=1;
	Lthis.a3.removeChild(Lthis.a2);
	LbubbleContainer.a0.removeChild(Lthis.a3);
}
function __ZNSt12__deque_baseI6BubbleSaIS0_EE3endEv(Lagg$presult,Lthis){
	var tmp0=null,tmp0o=0,Ladd=0,Lcond=null,Lcondo=0;
	tmp0o=Lthis.a1o;
	tmp0=Lthis.a1;
	Ladd=(Lthis.i4|0)+(Lthis.i5|0)|0;
	Lcondo=Lthis.a2o;
	Lcond=Lthis.a2;
	if(Lcond===tmp0&&Lcondo===tmp0o){
		Lcondo=0;
		Lcond=nullArray;
	}else{
		Lcond=tmp0[tmp0o+((Ladd>>>0)/124|0)|0];
		Lcondo=Lcond.o+((Ladd>>>0)%124|0)|0;
		Lcond=Lcond.d;
	}
	Lagg$presult.a0=tmp0;
	Lagg$presult.a0o=tmp0o+((Ladd>>>0)/124|0)|0;
	Lagg$presult.a1=Lcond;
	Lagg$presult.a1o=Lcondo;
}
function __ZNSt12__deque_baseI6BubbleSaIS0_EE5beginEv(Lagg$presult,Lthis){
	var tmp0=null,tmp0o=0,tmp1=0,Lcond=null,Lcondo=0;
	tmp0o=Lthis.a1o;
	tmp0=Lthis.a1;
	tmp1=Lthis.i4|0;
	Lcondo=Lthis.a2o;
	Lcond=Lthis.a2;
	if(Lcond===tmp0&&Lcondo===tmp0o){
		Lcondo=0;
		Lcond=nullArray;
	}else{
		Lcond=tmp0[tmp0o+((tmp1>>>0)/124|0)|0];
		Lcondo=Lcond.o+((tmp1>>>0)%124|0)|0;
		Lcond=Lcond.d;
	}
	Lagg$presult.a0=tmp0;
	Lagg$presult.a0o=tmp0o+((tmp1>>>0)/124|0)|0;
	Lagg$presult.a1=Lcond;
	Lagg$presult.a1o=Lcondo;
}
function __ZN15BubbleContainer6insertEPN6client11HTMLElementE(Lthis,Linner){
	var L__begin=null,tmp1=null,tmp1o=0,tmp2=null,L$ppre$mphi=null,L$ppre$mphio=0,L__end=null,L__endo=0;
	L$ppre$mphi=Lthis.a1;
	if(L$ppre$mphi!==null){
		L$ppre$mphi=L$ppre$mphi;
	}else{
		L$ppre$mphi={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:L$ppre$mphi={a0:nullArray,a0o:0},i4:0,i5:0};
		L$ppre$mphi.a0=nullArray;
		L$ppre$mphi.a1=nullArray;
		L$ppre$mphi.a1o=0;
		L$ppre$mphi.a2=nullArray;
		L$ppre$mphi.a2o=0;
		L$ppre$mphi.a3.a0=nullArray;
		L$ppre$mphi.a3.a0o=0;
		L$ppre$mphi.i4=0;
		L$ppre$mphi.i5=0;
		Lthis.a1=L$ppre$mphi;
		L$ppre$mphi=L$ppre$mphi;
	}
	L__begin={a0:nullArray,a0o:0,a1:nullArray,a1o:0};
	__ZNSt12__deque_baseI6BubbleSaIS0_EE5beginEv(L__begin,L$ppre$mphi);
	L__end={a0:nullArray,a0o:0,a1:nullArray,a1o:0};
	__ZNSt12__deque_baseI6BubbleSaIS0_EE3endEv(L__end,L$ppre$mphi);
	L$ppre$mphio=L__begin.a1o;
	L$ppre$mphi=L__begin.a1;
	L__endo=L__end.a1o;
	L__end=L__end.a1;
	a:{
		if(L$ppre$mphi!==L__end||L$ppre$mphio!==L__endo){
			while(1){
				if(L$ppre$mphi[L$ppre$mphio].a2===Linner){
					L__begin.a1=L$ppre$mphi;
					L__begin.a1o=L$ppre$mphio;
					break a;
				}
				tmp1o=L__begin.a0o;
				tmp1=L__begin.a0;
				tmp2=tmp1[tmp1o];
				if(((Math.imul(L$ppre$mphio+1|0,33))-(Math.imul(tmp2.o,33))|0)===4092){
					L__begin.a0=tmp1;
					L__begin.a0o=tmp1o+1|0;
					L$ppre$mphi=tmp1[tmp1o+1|0];
					L$ppre$mphio=L$ppre$mphi.o;
					L$ppre$mphi=L$ppre$mphi.d;
				}else{
					L$ppre$mphio=L$ppre$mphio+1|0;
					L$ppre$mphi=L$ppre$mphi;
				}
				if(L$ppre$mphi!==L__end||L$ppre$mphio!==L__endo)continue;
				break;
			}
			L__begin.a1=L__end;
			L__begin.a1o=L__endo;
		}
		__ZN15BubbleContainer9addBubbleEPN6client11HTMLElementE(Lthis,Linner);
	}
}
function __ZN15BubbleContainer9addBubbleEPN6client11HTMLElementE(Lthis,Linner){
	var Linner$paddr=null,tmp1=null;
	Linner$paddr=[Linner];
	tmp1=Lthis.a1;
	if(tmp1!==null){
		__ZNSt5dequeI6BubbleSaIS0_EE12emplace_backIJR15BubbleContainerRPN6client11HTMLElementEEEEvDpOT_(tmp1,Lthis,Linner$paddr,0);
		return;
	}
	tmp1={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:tmp1={a0:nullArray,a0o:0},i4:0,i5:0};
	tmp1.a0=nullArray;
	tmp1.a1=nullArray;
	tmp1.a1o=0;
	tmp1.a2=nullArray;
	tmp1.a2o=0;
	tmp1.a3.a0=nullArray;
	tmp1.a3.a0o=0;
	tmp1.i4=0;
	tmp1.i5=0;
	Lthis.a1=tmp1;
	__ZNSt5dequeI6BubbleSaIS0_EE12emplace_backIJR15BubbleContainerRPN6client11HTMLElementEEEEvDpOT_(tmp1,Lthis,Linner$paddr,0);
}
function __ZNSt5dequeI6BubbleSaIS0_EE12emplace_backIJR15BubbleContainerRPN6client11HTMLElementEEEEvDpOT_(Lthis,L__args,L__args1,M__args1){
	var tmp0=null,tmp0o=0,Lsub$pptr$plhs$pcast$pi$pi$pi=0,Ltmp=null,Ltmpo=0,Lsub$pptr$prhs$pcast$pi$pi$pi=0;
	Ltmpo=Lthis.a2o;
	Ltmp=Lthis.a2;
	tmp0o=Lthis.a1o;
	tmp0=Lthis.a1;
	Lsub$pptr$prhs$pcast$pi$pi$pi=(Math.imul(tmp0o,4));
	Lsub$pptr$plhs$pcast$pi$pi$pi=(Math.imul(Ltmpo,4));
	if((Lsub$pptr$plhs$pcast$pi$pi$pi|0)===(Lsub$pptr$prhs$pcast$pi$pi$pi|0)){
		Lsub$pptr$prhs$pcast$pi$pi$pi=0;
	}else{
		Lsub$pptr$prhs$pcast$pi$pi$pi=(__imul(Lsub$pptr$plhs$pcast$pi$pi$pi-Lsub$pptr$prhs$pcast$pi$pi$pi>>2,124)|0)-1|0;
	}
	if((Lsub$pptr$prhs$pcast$pi$pi$pi|0)===((Lthis.i5|0)+(Lthis.i4|0)|0))__ZNSt5dequeI6BubbleSaIS0_EE19__add_back_capacityEv(Lthis);
	Ltmp={a0:nullArray,a0o:0,a1:nullArray,a1o:0};
	__ZNSt12__deque_baseI6BubbleSaIS0_EE3endEv(Ltmp,Lthis);
	Ltmpo=Ltmp.a1o;
	Ltmp=Ltmp.a1;
	__ZN6BubbleC2ER15BubbleContainerPN6client11HTMLElementE(Ltmp[Ltmpo],L__args,L__args1[M__args1]);
	Lthis.i5=(Lthis.i5|0)+1|0;
}
function __ZN6BubbleC2ER15BubbleContainerPN6client11HTMLElementE(Lthis,Lcontainer,Linner){
	var Lmul=-0.,Lsub=-0.,Lcall2=null;
	Lthis.i4=0;
	Lthis.a2=Linner;
	Lthis.a3=document.createElement("div");
	Lcall2=Linner.style;
	Lcall2.height="100%";
	Lcall2.width="auto";
	Lcall2.backgroundColor="white";
	Lthis.a3.appendChild(Linner);
	Lcall2=Lthis.a3.style;
	Lcall2.overflow="hidden";
	Lcall2.position="absolute";
	Lcall2.borderRadius="50%";
	Lcall2.justifyContent="center";
	Lcall2.display="flex";
	Lcontainer.a0.appendChild(Lthis.a3);
	Lthis.a5[0]=0;
	Lmul=(+(_rand()|0|0))/2147483647*4;
	Lsub=Lmul-(+(~~Lmul|0));
	a:{
		if(Lmul<2){
			Lthis.d0=Lsub;
			if(Lmul>=1){
				Lthis.a1[0]=1;
				break a;
			}
		}else Lthis.a1[0]=Lsub;
		if(Lmul>=3)Lthis.d0=1;
	}
	__ZN6Bubble11setPositionEv(Lthis);
}
function _rand(){
	var tmp0=0,tmp1=0,tmp2=0,tmp3=0,tmp4=0,L$poptgep$poptgep$poptgepsqueezed=null,tmp6=0;
	L$poptgep$poptgep$poptgepsqueezed=_impure_data.a14;
	if(L$poptgep$poptgep$poptgepsqueezed===null){
		L$poptgep$poptgep$poptgepsqueezed={a0:new Uint16Array(6),i1:0,a2:new Int32Array(2)};
		_impure_data.a14=L$poptgep$poptgep$poptgepsqueezed;
		L$poptgep$poptgep$poptgepsqueezed=L$poptgep$poptgep$poptgepsqueezed.a0;
		L$poptgep$poptgep$poptgepsqueezed[0]=13070;
		L$poptgep$poptgep$poptgepsqueezed[1]=43981;
		L$poptgep$poptgep$poptgepsqueezed[2]=4660;
		L$poptgep$poptgep$poptgepsqueezed=_impure_data.a14.a0;
		L$poptgep$poptgep$poptgepsqueezed[3]=58989;
		L$poptgep$poptgep$poptgepsqueezed[4]=57068;
		L$poptgep$poptgep$poptgepsqueezed[5]=5;
		L$poptgep$poptgep$poptgepsqueezed=_impure_data.a14;
		L$poptgep$poptgep$poptgepsqueezed.i1=11;
		L$poptgep$poptgep$poptgepsqueezed=L$poptgep$poptgep$poptgepsqueezed.a2;
		L$poptgep$poptgep$poptgepsqueezed[1]=0;
		L$poptgep$poptgep$poptgepsqueezed[0]=1;
		L$poptgep$poptgep$poptgepsqueezed=_impure_data.a14;
	}
	L$poptgep$poptgep$poptgepsqueezed=L$poptgep$poptgep$poptgepsqueezed.a2;
	tmp0=L$poptgep$poptgep$poptgepsqueezed[0]|0;
	tmp1=tmp0>>>16;
	tmp6=tmp0&65535;
	tmp2=(__imul(tmp1,32557)|0)+(__imul(tmp6,19605)|0)|0;
	tmp3=tmp2<<16;
	tmp6=__imul(tmp6,32557)|0;
	tmp4=tmp3+tmp6|0;
	L$poptgep$poptgep$poptgepsqueezed[1]=(((((__imul(tmp0,1481765933)|0)+(__imul(L$poptgep$poptgep$poptgepsqueezed[1]|0,1284865837)|0)|0)+(__imul(tmp1,19605)|0)|0)+(tmp2>>>16)|0)+(tmp3>>>0>(tmp6^ -1)>>>0?1:0)|0)+((tmp4|0)===-1?1:0)|0;
	L$poptgep$poptgep$poptgepsqueezed[0]=tmp4+1|0;
	return _impure_data.a14.a2[1]&2147483647|0;
}
function __ZNSt5dequeI6BubbleSaIS0_EE19__add_back_capacityEv(Lthis){
	var Lsub$pptr$psub$pi=0,L__t$pi52=null,L__t$pi52o=0,Lref$ptmp=null,Lref$ptmpo=0,L__buf=null,L__bufo=0,L$ppre10=null,L$ppre10o=0,L__end_cap_$pi$pi$poptgepsqueezed=null,L__end_cap_$pi$pi$poptgepsqueezedo=0,L__end_cap_$pi$pi64$poptgepsqueezed=null,L__end_cap_$pi$pi64$poptgepsqueezedo=0,Lsub$pptr$plhs$pcast$pi=0,Lidx$pneg$pi=0,Ladd$pptr$pi$padd=0,Lsub$pptr$psub$pi$pi$pi=0,Lsub$pptr$pdiv$pi$pi$pi=0;
	Lsub$pptr$psub$pi=Lthis.i4|0;
	L__t$pi52={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:{a0:nullArray,a0o:0,a1:null}};
	if(Lsub$pptr$psub$pi>>>0>123){
		Lthis.i4=Lsub$pptr$psub$pi-124|0;
		Lref$ptmpo=Lthis.a1o;
		Lref$ptmp=Lthis.a1;
		L__buf=Lref$ptmp[Lref$ptmpo];
		Lthis.a1=Lref$ptmp;
		Lthis.a1o=Lref$ptmpo+1|0;
		L$ppre10o=Lthis.a2o;
		L$ppre10=Lthis.a2;
		L__end_cap_$pi$pi$poptgepsqueezed=Lthis.a3;
		L__end_cap_$pi$pi64$poptgepsqueezedo=L__end_cap_$pi$pi$poptgepsqueezed.a0o;
		L__end_cap_$pi$pi64$poptgepsqueezed=L__end_cap_$pi$pi$poptgepsqueezed.a0;
		if(L$ppre10===L__end_cap_$pi$pi64$poptgepsqueezed&&L$ppre10o===L__end_cap_$pi$pi64$poptgepsqueezedo){
			L__end_cap_$pi$pi64$poptgepsqueezed=Lthis.a0;
			if((Lref$ptmpo+1|0)>0){
				Lsub$pptr$plhs$pcast$pi=(Math.imul(Lref$ptmpo+1|0,4));
				Lsub$pptr$psub$pi=Lsub$pptr$plhs$pcast$pi-(Math.imul(0,4))|0;
				Lidx$pneg$pi=((Lsub$pptr$psub$pi>>2)+1|0)/-2|0;
				Ladd$pptr$pi$padd=Lidx$pneg$pi+1|0;
				Lsub$pptr$psub$pi$pi$pi=(Math.imul(L$ppre10o,4))-Lsub$pptr$plhs$pcast$pi|0;
				Lsub$pptr$pdiv$pi$pi$pi=Lsub$pptr$psub$pi$pi$pi>>2;
				if((Lsub$pptr$pdiv$pi$pi$pi|0)!==0){
					Lsub$pptr$psub$pi$pi$pi>>>=2;
					if((Lsub$pptr$psub$pi$pi$pi|0)!==0){
						Lsub$pptr$plhs$pcast$pi=Ladd$pptr$pi$padd+Lsub$pptr$psub$pi$pi$pi|0;
						if((Lsub$pptr$psub$pi|0)>-12){
							Lsub$pptr$psub$pi=Ladd$pptr$pi$padd;
							Lsub$pptr$psub$pi$pi$pi=1;
							while(1){
								L__t$pi52=Lref$ptmp[Lref$ptmpo+Lsub$pptr$psub$pi$pi$pi|0];
								Lref$ptmp[Lref$ptmpo+Lsub$pptr$psub$pi|0]=L__t$pi52;
								Lsub$pptr$psub$pi=Lsub$pptr$psub$pi+1|0;
								if(Lref$ptmp!==Lref$ptmp||(Lref$ptmpo+Lsub$pptr$plhs$pcast$pi|0)!==(Lref$ptmpo+Lsub$pptr$psub$pi|0)){
									Lsub$pptr$psub$pi$pi$pi=Lsub$pptr$psub$pi$pi$pi+1|0;
									continue;
								}
								break;
							}
						}else{
							Lsub$pptr$psub$pi$pi$pi=1+Lsub$pptr$psub$pi$pi$pi|0;
							while(1){
								Lsub$pptr$psub$pi$pi$pi=Lsub$pptr$psub$pi$pi$pi-1|0;
								Lsub$pptr$plhs$pcast$pi=Lsub$pptr$plhs$pcast$pi-1|0;
								L__t$pi52=Lref$ptmp[Lref$ptmpo+Lsub$pptr$psub$pi$pi$pi|0];
								Lref$ptmp[Lref$ptmpo+Lsub$pptr$plhs$pcast$pi|0]=L__t$pi52;
								if(Lref$ptmp!==Lref$ptmp||(Lref$ptmpo+Ladd$pptr$pi$padd|0)!==(Lref$ptmpo+Lsub$pptr$plhs$pcast$pi|0))continue;
								break;
							}
						}
					}
					L__t$pi52o=Lthis.a1o;
					L__t$pi52=Lthis.a1;
				}else{
					L__t$pi52o=Lref$ptmpo+1|0;
					L__t$pi52=Lref$ptmp;
				}
				Lthis.a2=Lref$ptmp;
				Lthis.a2o=(Lref$ptmpo+Ladd$pptr$pi$padd|0)+Lsub$pptr$pdiv$pi$pi$pi|0;
				Lthis.a1=L__t$pi52;
				Lthis.a1o=L__t$pi52o+Lidx$pneg$pi|0;
				L$ppre10o=(Lref$ptmpo+Ladd$pptr$pi$padd|0)+Lsub$pptr$pdiv$pi$pi$pi|0;
				L$ppre10=Lref$ptmp;
			}else{
				Lsub$pptr$psub$pi=(Math.imul(L$ppre10o,4))-(Math.imul(0,4))>>1;
				Lsub$pptr$psub$pi=(Lsub$pptr$psub$pi|0)!==0?Lsub$pptr$psub$pi|0:1|0;
				__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__t$pi52,Lsub$pptr$psub$pi,Lsub$pptr$psub$pi>>>2,L__end_cap_$pi$pi$poptgepsqueezed);
				Lref$ptmpo=Lthis.a1o;
				Lref$ptmp=Lthis.a1;
				L$ppre10o=Lthis.a2o;
				L$ppre10=Lthis.a2;
				__ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(L__t$pi52,Lref$ptmp,Lref$ptmpo,L$ppre10,L$ppre10o);
				Lref$ptmp=Lthis.a0;
				L$ppre10=L__t$pi52.a0;
				Lthis.a0=L$ppre10;
				L__t$pi52.a0=Lref$ptmp;
				Lref$ptmpo=Lthis.a1o;
				Lref$ptmp=Lthis.a1;
				L$ppre10o=L__t$pi52.a1o;
				L$ppre10=L__t$pi52.a1;
				Lthis.a1=L$ppre10;
				Lthis.a1o=L$ppre10o;
				L__t$pi52.a1=Lref$ptmp;
				L__t$pi52.a1o=Lref$ptmpo;
				Lref$ptmpo=Lthis.a2o;
				Lref$ptmp=Lthis.a2;
				L$ppre10o=L__t$pi52.a2o;
				L$ppre10=L__t$pi52.a2;
				Lthis.a2=L$ppre10;
				Lthis.a2o=L$ppre10o;
				L__t$pi52.a2=Lref$ptmp;
				L__t$pi52.a2o=Lref$ptmpo;
				Lref$ptmpo=L__end_cap_$pi$pi$poptgepsqueezed.a0o;
				Lref$ptmp=L__end_cap_$pi$pi$poptgepsqueezed.a0;
				L$ppre10o=L__t$pi52.a3.a0o;
				L$ppre10=L__t$pi52.a3.a0;
				L__end_cap_$pi$pi$poptgepsqueezed.a0=L$ppre10;
				L__end_cap_$pi$pi$poptgepsqueezed.a0o=L$ppre10o;
				L__t$pi52.a3.a0=Lref$ptmp;
				L__t$pi52.a3.a0o=Lref$ptmpo;
				__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__t$pi52);
				L$ppre10o=Lthis.a2o;
				L$ppre10=Lthis.a2;
			}
		}
		L$ppre10[L$ppre10o]=L__buf;
		L__t$pi52o=Lthis.a2o;
		L__t$pi52=Lthis.a2;
		Lthis.a2=L__t$pi52;
		Lthis.a2o=L__t$pi52o+1|0;
	}else{
		Lref$ptmpo=Lthis.a2o;
		Lref$ptmp=Lthis.a2;
		L__bufo=Lthis.a1o;
		L__buf=Lthis.a1;
		Lsub$pptr$plhs$pcast$pi=(Math.imul(Lref$ptmpo,4));
		Lsub$pptr$pdiv$pi$pi$pi=Lsub$pptr$plhs$pcast$pi-(Math.imul(L__bufo,4))|0;
		L__end_cap_$pi$pi64$poptgepsqueezed=Lthis.a3;
		Lref$ptmpo=L__end_cap_$pi$pi64$poptgepsqueezed.a0o;
		Lref$ptmp=L__end_cap_$pi$pi64$poptgepsqueezed.a0;
		L__buf=Lthis.a0;
		Lsub$pptr$psub$pi$pi$pi=(Math.imul(Lref$ptmpo,4));
		Lsub$pptr$psub$pi=Lsub$pptr$psub$pi$pi$pi-(Math.imul(0,4))|0;
		Lref$ptmp=[nullObj];
		if(Lsub$pptr$pdiv$pi$pi$pi>>>0<Lsub$pptr$psub$pi>>>0){
			L__buf=createArray_class$p_Z6Bubble(124);
			if((Lsub$pptr$psub$pi$pi$pi|0)===(Lsub$pptr$plhs$pcast$pi|0)){
				Lref$ptmp[0]={d:L__buf,o:0};
				__ZNSt14__split_bufferIP6BubbleSaIS1_EE10push_frontEOS1_(Lthis,Lref$ptmp,0);
				Lref$ptmpo=Lthis.a1o;
				Lref$ptmp=Lthis.a1;
				L__buf=Lref$ptmp[Lref$ptmpo];
				Lthis.a1=Lref$ptmp;
				Lthis.a1o=Lref$ptmpo+1|0;
				L$ppre10o=Lthis.a2o;
				L$ppre10=Lthis.a2;
				L__end_cap_$pi$pi$poptgepsqueezedo=L__end_cap_$pi$pi64$poptgepsqueezed.a0o;
				L__end_cap_$pi$pi$poptgepsqueezed=L__end_cap_$pi$pi64$poptgepsqueezed.a0;
				if(L$ppre10===L__end_cap_$pi$pi$poptgepsqueezed&&L$ppre10o===L__end_cap_$pi$pi$poptgepsqueezedo){
					L__end_cap_$pi$pi$poptgepsqueezed=Lthis.a0;
					if((Lref$ptmpo+1|0)>0){
						Lsub$pptr$plhs$pcast$pi=(Math.imul(Lref$ptmpo+1|0,4));
						Lsub$pptr$psub$pi=Lsub$pptr$plhs$pcast$pi-(Math.imul(0,4))|0;
						Lidx$pneg$pi=((Lsub$pptr$psub$pi>>2)+1|0)/-2|0;
						Ladd$pptr$pi$padd=Lidx$pneg$pi+1|0;
						Lsub$pptr$psub$pi$pi$pi=(Math.imul(L$ppre10o,4))-Lsub$pptr$plhs$pcast$pi|0;
						Lsub$pptr$pdiv$pi$pi$pi=Lsub$pptr$psub$pi$pi$pi>>2;
						if((Lsub$pptr$pdiv$pi$pi$pi|0)!==0){
							Lsub$pptr$psub$pi$pi$pi>>>=2;
							if((Lsub$pptr$psub$pi$pi$pi|0)!==0){
								Lsub$pptr$plhs$pcast$pi=Ladd$pptr$pi$padd+Lsub$pptr$psub$pi$pi$pi|0;
								if((Lsub$pptr$psub$pi|0)>-12){
									Lsub$pptr$psub$pi=Ladd$pptr$pi$padd;
									Lsub$pptr$psub$pi$pi$pi=1;
									while(1){
										L$ppre10=Lref$ptmp[Lref$ptmpo+Lsub$pptr$psub$pi$pi$pi|0];
										Lref$ptmp[Lref$ptmpo+Lsub$pptr$psub$pi|0]=L$ppre10;
										Lsub$pptr$psub$pi=Lsub$pptr$psub$pi+1|0;
										if(Lref$ptmp!==Lref$ptmp||(Lref$ptmpo+Lsub$pptr$plhs$pcast$pi|0)!==(Lref$ptmpo+Lsub$pptr$psub$pi|0)){
											Lsub$pptr$psub$pi$pi$pi=Lsub$pptr$psub$pi$pi$pi+1|0;
											continue;
										}
										break;
									}
								}else{
									Lsub$pptr$psub$pi$pi$pi=1+Lsub$pptr$psub$pi$pi$pi|0;
									while(1){
										Lsub$pptr$psub$pi$pi$pi=Lsub$pptr$psub$pi$pi$pi-1|0;
										Lsub$pptr$plhs$pcast$pi=Lsub$pptr$plhs$pcast$pi-1|0;
										L$ppre10=Lref$ptmp[Lref$ptmpo+Lsub$pptr$psub$pi$pi$pi|0];
										Lref$ptmp[Lref$ptmpo+Lsub$pptr$plhs$pcast$pi|0]=L$ppre10;
										if(Lref$ptmp!==Lref$ptmp||(Lref$ptmpo+Ladd$pptr$pi$padd|0)!==(Lref$ptmpo+Lsub$pptr$plhs$pcast$pi|0))continue;
										break;
									}
								}
							}
							L$ppre10o=Lthis.a1o;
							L$ppre10=Lthis.a1;
						}else{
							L$ppre10o=Lref$ptmpo+1|0;
							L$ppre10=Lref$ptmp;
						}
						Lthis.a2=Lref$ptmp;
						Lthis.a2o=(Lref$ptmpo+Ladd$pptr$pi$padd|0)+Lsub$pptr$pdiv$pi$pi$pi|0;
						Lthis.a1=L$ppre10;
						Lthis.a1o=L$ppre10o+Lidx$pneg$pi|0;
						L$ppre10o=(Lref$ptmpo+Ladd$pptr$pi$padd|0)+Lsub$pptr$pdiv$pi$pi$pi|0;
						L$ppre10=Lref$ptmp;
					}else{
						Lsub$pptr$psub$pi=(Math.imul(L$ppre10o,4))-(Math.imul(0,4))>>1;
						Lsub$pptr$psub$pi=(Lsub$pptr$psub$pi|0)!==0?Lsub$pptr$psub$pi|0:1|0;
						__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__t$pi52,Lsub$pptr$psub$pi,Lsub$pptr$psub$pi>>>2,L__end_cap_$pi$pi64$poptgepsqueezed);
						Lref$ptmpo=Lthis.a1o;
						Lref$ptmp=Lthis.a1;
						L$ppre10o=Lthis.a2o;
						L$ppre10=Lthis.a2;
						__ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(L__t$pi52,Lref$ptmp,Lref$ptmpo,L$ppre10,L$ppre10o);
						Lref$ptmp=Lthis.a0;
						L$ppre10=L__t$pi52.a0;
						Lthis.a0=L$ppre10;
						L__t$pi52.a0=Lref$ptmp;
						Lref$ptmpo=Lthis.a1o;
						Lref$ptmp=Lthis.a1;
						L$ppre10o=L__t$pi52.a1o;
						L$ppre10=L__t$pi52.a1;
						Lthis.a1=L$ppre10;
						Lthis.a1o=L$ppre10o;
						L__t$pi52.a1=Lref$ptmp;
						L__t$pi52.a1o=Lref$ptmpo;
						Lref$ptmpo=Lthis.a2o;
						Lref$ptmp=Lthis.a2;
						L$ppre10o=L__t$pi52.a2o;
						L$ppre10=L__t$pi52.a2;
						Lthis.a2=L$ppre10;
						Lthis.a2o=L$ppre10o;
						L__t$pi52.a2=Lref$ptmp;
						L__t$pi52.a2o=Lref$ptmpo;
						Lref$ptmpo=L__end_cap_$pi$pi64$poptgepsqueezed.a0o;
						Lref$ptmp=L__end_cap_$pi$pi64$poptgepsqueezed.a0;
						L$ppre10o=L__t$pi52.a3.a0o;
						L$ppre10=L__t$pi52.a3.a0;
						L__end_cap_$pi$pi64$poptgepsqueezed.a0=L$ppre10;
						L__end_cap_$pi$pi64$poptgepsqueezed.a0o=L$ppre10o;
						L__t$pi52.a3.a0=Lref$ptmp;
						L__t$pi52.a3.a0o=Lref$ptmpo;
						__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__t$pi52);
						L$ppre10o=Lthis.a2o;
						L$ppre10=Lthis.a2;
					}
				}
				L$ppre10[L$ppre10o]=L__buf;
				L__t$pi52o=Lthis.a2o;
				L__t$pi52=Lthis.a2;
				Lthis.a2=L__t$pi52;
				Lthis.a2o=L__t$pi52o+1|0;
			}else{
				Lref$ptmp[0]={d:L__buf,o:0};
				__ZNSt14__split_bufferIP6BubbleSaIS1_EE9push_backEOS1_(Lthis,Lref$ptmp,0);
			}
		}else{
			Lsub$pptr$psub$pi>>=1;
			L__buf={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:{a0:nullArray,a0o:0,a1:null}};
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__buf,(Lsub$pptr$psub$pi|0)!==0?Lsub$pptr$psub$pi|0:1|0,Lsub$pptr$pdiv$pi$pi$pi>>2,L__end_cap_$pi$pi64$poptgepsqueezed);
			L$ppre10=createArray_class$p_Z6Bubble(124);
			Lref$ptmp[0]={d:L$ppre10,o:0};
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EE9push_backEOS1_(L__buf,Lref$ptmp,0);
			L$ppre10o=Lthis.a2o;
			L$ppre10=Lthis.a2;
			Lref$ptmpo=Lthis.a1o;
			Lref$ptmp=Lthis.a1;
			if(L$ppre10===Lref$ptmp&&L$ppre10o===Lref$ptmpo){
				Lref$ptmpo=L$ppre10o;
				Lref$ptmp=L$ppre10;
				Lsub$pptr$psub$pi=0;
			}else{
				Lsub$pptr$psub$pi=0;
				while(1){
					Lsub$pptr$psub$pi=Lsub$pptr$psub$pi-1|0;
					__ZNSt14__split_bufferIP6BubbleRSaIS1_EE10push_frontERKS1_(L__buf,L$ppre10,L$ppre10o+Lsub$pptr$psub$pi|0);
					Lref$ptmpo=Lthis.a1o;
					Lref$ptmp=Lthis.a1;
					if(L$ppre10!==Lref$ptmp||(L$ppre10o+Lsub$pptr$psub$pi|0)!==Lref$ptmpo)continue;
					break;
				}
				Lref$ptmpo=Lthis.a2o;
				Lref$ptmp=Lthis.a2;
			}
			L__t$pi52=Lthis.a0;
			L__end_cap_$pi$pi$poptgepsqueezed=L__buf.a0;
			Lthis.a0=L__end_cap_$pi$pi$poptgepsqueezed;
			L__buf.a0=L__t$pi52;
			L__t$pi52o=L__buf.a1o;
			L__t$pi52=L__buf.a1;
			Lthis.a1=L__t$pi52;
			Lthis.a1o=L__t$pi52o;
			L__buf.a1=L$ppre10;
			L__buf.a1o=L$ppre10o+Lsub$pptr$psub$pi|0;
			L__t$pi52o=L__buf.a2o;
			L__t$pi52=L__buf.a2;
			Lthis.a2=L__t$pi52;
			Lthis.a2o=L__t$pi52o;
			L__buf.a2=Lref$ptmp;
			L__buf.a2o=Lref$ptmpo;
			L$ppre10o=L__end_cap_$pi$pi64$poptgepsqueezed.a0o;
			L$ppre10=L__end_cap_$pi$pi64$poptgepsqueezed.a0;
			Lref$ptmpo=L__buf.a3.a0o;
			Lref$ptmp=L__buf.a3.a0;
			L__end_cap_$pi$pi64$poptgepsqueezed.a0=Lref$ptmp;
			L__end_cap_$pi$pi64$poptgepsqueezed.a0o=Lref$ptmpo;
			L__buf.a3.a0=L$ppre10;
			L__buf.a3.a0o=L$ppre10o;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__buf);
		}
	}
}
function __ZNSt14__split_bufferIP6BubbleRSaIS1_EE10push_frontERKS1_(Lthis,L__x,M__x){
	var L$ppre1=null,L$ppre1o=0,L__t=null,L__to=0,L$ppre=null,L$ppreo=0,tmp3=null,tmp3o=0,Lsub$pptr$plhs$pcast=0,Lsub$pptr$prhs$pcast=0,Lsub$pptr$pdiv$pi$pi=0,Lgeptoindex=0,Lgeptoindexphi6=0;
	L$ppre1o=Lthis.a1o;
	L$ppre1=Lthis.a1;
	L__t=Lthis.a0;
	if(L$ppre1===L__t&&L$ppre1o===0){
		L__to=Lthis.a2o;
		L__t=Lthis.a2;
		L$ppre=Lthis.a3;
		tmp3o=L$ppre.a0o;
		tmp3=L$ppre.a0;
		Lsub$pptr$plhs$pcast=(Math.imul(tmp3o,4));
		if(L__to<tmp3o){
			Lsub$pptr$prhs$pcast=(Math.imul(L__to,4));
			Lsub$pptr$plhs$pcast=((Lsub$pptr$plhs$pcast-Lsub$pptr$prhs$pcast>>2)+1|0)/2|0;
			Lsub$pptr$prhs$pcast=Lsub$pptr$prhs$pcast-(Math.imul(L$ppre1o,4))|0;
			Lsub$pptr$pdiv$pi$pi=Lsub$pptr$prhs$pcast>>2;
			if((Lsub$pptr$pdiv$pi$pi|0)!==0){
				Lgeptoindex=Lsub$pptr$plhs$pcast+(-Lsub$pptr$pdiv$pi$pi|0)|0;
				Lsub$pptr$prhs$pcast>>>=2;
				if((Lsub$pptr$prhs$pcast|0)!==0){
					Lsub$pptr$pdiv$pi$pi=Lgeptoindex+Lsub$pptr$prhs$pcast|0;
					if(L$ppre1o<(L__to+Lgeptoindex|0))while(1){
						Lsub$pptr$prhs$pcast=Lsub$pptr$prhs$pcast-1|0;
						Lsub$pptr$pdiv$pi$pi=Lsub$pptr$pdiv$pi$pi-1|0;
						L$ppre=L$ppre1[L$ppre1o+Lsub$pptr$prhs$pcast|0];
						L__t[L__to+Lsub$pptr$pdiv$pi$pi|0]=L$ppre;
						if(L__t!==L__t||(L__to+Lgeptoindex|0)!==(L__to+Lsub$pptr$pdiv$pi$pi|0))continue;
						break;
					}
					else{
						Lgeptoindexphi6=Lgeptoindex;
						Lsub$pptr$prhs$pcast=0;
						while(1){
							L$ppre=L$ppre1[L$ppre1o+Lsub$pptr$prhs$pcast|0];
							L__t[L__to+Lgeptoindexphi6|0]=L$ppre;
							Lgeptoindexphi6=Lgeptoindexphi6+1|0;
							if(L__t!==L__t||(L__to+Lsub$pptr$pdiv$pi$pi|0)!==(L__to+Lgeptoindexphi6|0)){
								Lsub$pptr$prhs$pcast=Lsub$pptr$prhs$pcast+1|0;
								continue;
							}
							break;
						}
					}
				}
				L$ppreo=Lthis.a2o;
				L$ppre=Lthis.a2;
			}else{
				L$ppreo=L__to;
				L$ppre=L__t;
				Lgeptoindex=Lsub$pptr$plhs$pcast;
			}
			Lthis.a1=L__t;
			Lthis.a1o=L__to+Lgeptoindex|0;
			Lthis.a2=L$ppre;
			Lthis.a2o=L$ppreo+Lsub$pptr$plhs$pcast|0;
			L$ppre1o=L__to+Lgeptoindex|0;
			L$ppre1=L__t;
		}else{
			Lsub$pptr$plhs$pcast=Lsub$pptr$plhs$pcast-(Math.imul(L$ppre1o,4))>>1;
			Lsub$pptr$plhs$pcast=(Lsub$pptr$plhs$pcast|0)!==0?Lsub$pptr$plhs$pcast|0:1|0;
			L__t={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:{a0:nullArray,a0o:0,a1:null}};
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__t,Lsub$pptr$plhs$pcast,Lsub$pptr$plhs$pcast+3>>>2,L$ppre.a1);
			tmp3o=Lthis.a1o;
			tmp3=Lthis.a1;
			L$ppre1o=Lthis.a2o;
			L$ppre1=Lthis.a2;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(L__t,tmp3,tmp3o,L$ppre1,L$ppre1o);
			tmp3=Lthis.a0;
			L$ppre1=L__t.a0;
			Lthis.a0=L$ppre1;
			L__t.a0=tmp3;
			tmp3o=Lthis.a1o;
			tmp3=Lthis.a1;
			L$ppre1o=L__t.a1o;
			L$ppre1=L__t.a1;
			Lthis.a1=L$ppre1;
			Lthis.a1o=L$ppre1o;
			L__t.a1=tmp3;
			L__t.a1o=tmp3o;
			tmp3o=Lthis.a2o;
			tmp3=Lthis.a2;
			L$ppre1o=L__t.a2o;
			L$ppre1=L__t.a2;
			Lthis.a2=L$ppre1;
			Lthis.a2o=L$ppre1o;
			L__t.a2=tmp3;
			L__t.a2o=tmp3o;
			tmp3o=L$ppre.a0o;
			tmp3=L$ppre.a0;
			L$ppre1o=L__t.a3.a0o;
			L$ppre1=L__t.a3.a0;
			L$ppre.a0=L$ppre1;
			L$ppre.a0o=L$ppre1o;
			L__t.a3.a0=tmp3;
			L__t.a3.a0o=tmp3o;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__t);
			L$ppre1o=Lthis.a1o;
			L$ppre1=Lthis.a1;
		}
	}
	L__t=L__x[M__x];
	L$ppre1[L$ppre1o+ -1|0]=L__t;
	L$ppre1o=Lthis.a1o;
	L$ppre1=Lthis.a1;
	Lthis.a1=L$ppre1;
	Lthis.a1o=L$ppre1o+ -1|0;
}
function __ZNSt14__split_bufferIP6BubbleRSaIS1_EE9push_backEOS1_(Lthis,L__x,M__x){
	var Lidx$pneg=0,Lsub$pptr$pdiv$pi$pi=0,L__t=null,L__to=0,tmp3=null,tmp4=null,tmp4o=0,L$ppre=null,L$ppreo=0,Lsub$pptr$plhs$pcast=0,Lsub$pptr$psub=0,Lsub$pptr$psub$pi$pi=0;
	L__to=Lthis.a2o;
	L__t=Lthis.a2;
	tmp3=Lthis.a3;
	tmp4o=tmp3.a0o;
	tmp4=tmp3.a0;
	if(L__t===tmp4&&L__to===tmp4o){
		tmp4o=Lthis.a1o;
		tmp4=Lthis.a1;
		L$ppre=Lthis.a0;
		if(tmp4o>0){
			Lsub$pptr$plhs$pcast=(Math.imul(tmp4o,4));
			Lsub$pptr$psub=Lsub$pptr$plhs$pcast-(Math.imul(0,4))|0;
			Lidx$pneg=((Lsub$pptr$psub>>2)+1|0)/-2|0;
			Lsub$pptr$psub$pi$pi=(Math.imul(L__to,4))-Lsub$pptr$plhs$pcast|0;
			Lsub$pptr$pdiv$pi$pi=Lsub$pptr$psub$pi$pi>>2;
			if((Lsub$pptr$pdiv$pi$pi|0)!==0){
				Lsub$pptr$psub$pi$pi>>>=2;
				if((Lsub$pptr$psub$pi$pi|0)!==0){
					Lsub$pptr$plhs$pcast=Lidx$pneg+Lsub$pptr$psub$pi$pi|0;
					if((Lsub$pptr$psub|0)>-12){
						Lsub$pptr$psub=Lidx$pneg;
						Lsub$pptr$psub$pi$pi=0;
						while(1){
							L$ppre=tmp4[tmp4o+Lsub$pptr$psub$pi$pi|0];
							tmp4[tmp4o+Lsub$pptr$psub|0]=L$ppre;
							Lsub$pptr$psub=Lsub$pptr$psub+1|0;
							if(tmp4!==tmp4||(tmp4o+Lsub$pptr$plhs$pcast|0)!==(tmp4o+Lsub$pptr$psub|0)){
								Lsub$pptr$psub$pi$pi=Lsub$pptr$psub$pi$pi+1|0;
								continue;
							}
							break;
						}
					}else while(1){
						Lsub$pptr$psub$pi$pi=Lsub$pptr$psub$pi$pi-1|0;
						Lsub$pptr$plhs$pcast=Lsub$pptr$plhs$pcast-1|0;
						L$ppre=tmp4[tmp4o+Lsub$pptr$psub$pi$pi|0];
						tmp4[tmp4o+Lsub$pptr$plhs$pcast|0]=L$ppre;
						if(tmp4!==tmp4||(tmp4o+Lidx$pneg|0)!==(tmp4o+Lsub$pptr$plhs$pcast|0))continue;
						break;
					}
				}
				L$ppreo=Lthis.a1o;
				L$ppre=Lthis.a1;
			}else{
				L$ppreo=tmp4o;
				L$ppre=tmp4;
			}
			Lthis.a2=tmp4;
			Lthis.a2o=(tmp4o+Lidx$pneg|0)+Lsub$pptr$pdiv$pi$pi|0;
			Lthis.a1=L$ppre;
			Lthis.a1o=L$ppreo+Lidx$pneg|0;
			L__to=(tmp4o+Lidx$pneg|0)+Lsub$pptr$pdiv$pi$pi|0;
			L__t=tmp4;
		}else{
			Lsub$pptr$psub=(Math.imul(L__to,4))-(Math.imul(0,4))>>1;
			Lsub$pptr$psub=(Lsub$pptr$psub|0)!==0?Lsub$pptr$psub|0:1|0;
			L__t={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:{a0:nullArray,a0o:0,a1:null}};
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__t,Lsub$pptr$psub,Lsub$pptr$psub>>>2,tmp3.a1);
			tmp4o=Lthis.a1o;
			tmp4=Lthis.a1;
			L$ppreo=Lthis.a2o;
			L$ppre=Lthis.a2;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(L__t,tmp4,tmp4o,L$ppre,L$ppreo);
			tmp4=Lthis.a0;
			L$ppre=L__t.a0;
			Lthis.a0=L$ppre;
			L__t.a0=tmp4;
			tmp4o=Lthis.a1o;
			tmp4=Lthis.a1;
			L$ppreo=L__t.a1o;
			L$ppre=L__t.a1;
			Lthis.a1=L$ppre;
			Lthis.a1o=L$ppreo;
			L__t.a1=tmp4;
			L__t.a1o=tmp4o;
			tmp4o=Lthis.a2o;
			tmp4=Lthis.a2;
			L$ppreo=L__t.a2o;
			L$ppre=L__t.a2;
			Lthis.a2=L$ppre;
			Lthis.a2o=L$ppreo;
			L__t.a2=tmp4;
			L__t.a2o=tmp4o;
			tmp4o=tmp3.a0o;
			tmp4=tmp3.a0;
			L$ppreo=L__t.a3.a0o;
			L$ppre=L__t.a3.a0;
			tmp3.a0=L$ppre;
			tmp3.a0o=L$ppreo;
			L__t.a3.a0=tmp4;
			L__t.a3.a0o=tmp4o;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__t);
			L__to=Lthis.a2o;
			L__t=Lthis.a2;
		}
	}
	tmp3=L__x[M__x];
	L__t[L__to]=tmp3;
	L__to=Lthis.a2o;
	L__t=Lthis.a2;
	Lthis.a2=L__t;
	Lthis.a2o=L__to+1|0;
}
function __ZNSt14__split_bufferIP6BubbleSaIS1_EE10push_frontEOS1_(Lthis,L__x,M__x){
	var L$ppre1=null,L$ppre1o=0,L__t=null,L__to=0,L__end_cap_$pi$poptgepsqueezed=null,L__end_cap_$pi$poptgepsqueezedo=0,tmp3=null,tmp3o=0,Lsub$pptr$plhs$pcast=0,Lsub$pptr$prhs$pcast=0,Lsub$pptr$pdiv$pi$pi=0,Lgeptoindex=0,Lgeptoindexphi6=0;
	L$ppre1o=Lthis.a1o;
	L$ppre1=Lthis.a1;
	L__t=Lthis.a0;
	if(L$ppre1===L__t&&L$ppre1o===0){
		L__to=Lthis.a2o;
		L__t=Lthis.a2;
		L__end_cap_$pi$poptgepsqueezed=Lthis.a3;
		tmp3o=L__end_cap_$pi$poptgepsqueezed.a0o;
		tmp3=L__end_cap_$pi$poptgepsqueezed.a0;
		Lsub$pptr$plhs$pcast=(Math.imul(tmp3o,4));
		if(L__to<tmp3o){
			Lsub$pptr$prhs$pcast=(Math.imul(L__to,4));
			Lsub$pptr$plhs$pcast=((Lsub$pptr$plhs$pcast-Lsub$pptr$prhs$pcast>>2)+1|0)/2|0;
			Lsub$pptr$prhs$pcast=Lsub$pptr$prhs$pcast-(Math.imul(L$ppre1o,4))|0;
			Lsub$pptr$pdiv$pi$pi=Lsub$pptr$prhs$pcast>>2;
			if((Lsub$pptr$pdiv$pi$pi|0)!==0){
				Lgeptoindex=Lsub$pptr$plhs$pcast+(-Lsub$pptr$pdiv$pi$pi|0)|0;
				Lsub$pptr$prhs$pcast>>>=2;
				if((Lsub$pptr$prhs$pcast|0)!==0){
					Lsub$pptr$pdiv$pi$pi=Lgeptoindex+Lsub$pptr$prhs$pcast|0;
					if(L$ppre1o<(L__to+Lgeptoindex|0))while(1){
						Lsub$pptr$prhs$pcast=Lsub$pptr$prhs$pcast-1|0;
						Lsub$pptr$pdiv$pi$pi=Lsub$pptr$pdiv$pi$pi-1|0;
						L__end_cap_$pi$poptgepsqueezed=L$ppre1[L$ppre1o+Lsub$pptr$prhs$pcast|0];
						L__t[L__to+Lsub$pptr$pdiv$pi$pi|0]=L__end_cap_$pi$poptgepsqueezed;
						if(L__t!==L__t||(L__to+Lgeptoindex|0)!==(L__to+Lsub$pptr$pdiv$pi$pi|0))continue;
						break;
					}
					else{
						Lgeptoindexphi6=Lgeptoindex;
						Lsub$pptr$prhs$pcast=0;
						while(1){
							L__end_cap_$pi$poptgepsqueezed=L$ppre1[L$ppre1o+Lsub$pptr$prhs$pcast|0];
							L__t[L__to+Lgeptoindexphi6|0]=L__end_cap_$pi$poptgepsqueezed;
							Lgeptoindexphi6=Lgeptoindexphi6+1|0;
							if(L__t!==L__t||(L__to+Lsub$pptr$pdiv$pi$pi|0)!==(L__to+Lgeptoindexphi6|0)){
								Lsub$pptr$prhs$pcast=Lsub$pptr$prhs$pcast+1|0;
								continue;
							}
							break;
						}
					}
				}
				L__end_cap_$pi$poptgepsqueezedo=Lthis.a2o;
				L__end_cap_$pi$poptgepsqueezed=Lthis.a2;
			}else{
				L__end_cap_$pi$poptgepsqueezedo=L__to;
				L__end_cap_$pi$poptgepsqueezed=L__t;
				Lgeptoindex=Lsub$pptr$plhs$pcast;
			}
			Lthis.a1=L__t;
			Lthis.a1o=L__to+Lgeptoindex|0;
			Lthis.a2=L__end_cap_$pi$poptgepsqueezed;
			Lthis.a2o=L__end_cap_$pi$poptgepsqueezedo+Lsub$pptr$plhs$pcast|0;
			L$ppre1o=L__to+Lgeptoindex|0;
			L$ppre1=L__t;
		}else{
			Lsub$pptr$plhs$pcast=Lsub$pptr$plhs$pcast-(Math.imul(L$ppre1o,4))>>1;
			Lsub$pptr$plhs$pcast=(Lsub$pptr$plhs$pcast|0)!==0?Lsub$pptr$plhs$pcast|0:1|0;
			L__t={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:{a0:nullArray,a0o:0,a1:null}};
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__t,Lsub$pptr$plhs$pcast,Lsub$pptr$plhs$pcast+3>>>2,L__end_cap_$pi$poptgepsqueezed);
			tmp3o=Lthis.a1o;
			tmp3=Lthis.a1;
			L$ppre1o=Lthis.a2o;
			L$ppre1=Lthis.a2;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(L__t,tmp3,tmp3o,L$ppre1,L$ppre1o);
			tmp3=Lthis.a0;
			L$ppre1=L__t.a0;
			Lthis.a0=L$ppre1;
			L__t.a0=tmp3;
			tmp3o=Lthis.a1o;
			tmp3=Lthis.a1;
			L$ppre1o=L__t.a1o;
			L$ppre1=L__t.a1;
			Lthis.a1=L$ppre1;
			Lthis.a1o=L$ppre1o;
			L__t.a1=tmp3;
			L__t.a1o=tmp3o;
			tmp3o=Lthis.a2o;
			tmp3=Lthis.a2;
			L$ppre1o=L__t.a2o;
			L$ppre1=L__t.a2;
			Lthis.a2=L$ppre1;
			Lthis.a2o=L$ppre1o;
			L__t.a2=tmp3;
			L__t.a2o=tmp3o;
			tmp3o=L__end_cap_$pi$poptgepsqueezed.a0o;
			tmp3=L__end_cap_$pi$poptgepsqueezed.a0;
			L$ppre1o=L__t.a3.a0o;
			L$ppre1=L__t.a3.a0;
			L__end_cap_$pi$poptgepsqueezed.a0=L$ppre1;
			L__end_cap_$pi$poptgepsqueezed.a0o=L$ppre1o;
			L__t.a3.a0=tmp3;
			L__t.a3.a0o=tmp3o;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__t);
			L$ppre1o=Lthis.a1o;
			L$ppre1=Lthis.a1;
		}
	}
	L__t=L__x[M__x];
	L$ppre1[L$ppre1o+ -1|0]=L__t;
	L$ppre1o=Lthis.a1o;
	L$ppre1=Lthis.a1;
	Lthis.a1=L$ppre1;
	Lthis.a1o=L$ppre1o+ -1|0;
}
function __ZNSt14__split_bufferIP6BubbleSaIS1_EE9push_backEOS1_(Lthis,L__x,M__x){
	var Lidx$pneg=0,Lsub$pptr$pdiv$pi$pi=0,L__t=null,L__to=0,L__end_cap_$pi$poptgepsqueezed=null,tmp4=null,tmp4o=0,L$ppre=null,L$ppreo=0,Lsub$pptr$plhs$pcast=0,Lsub$pptr$psub=0,Lsub$pptr$psub$pi$pi=0;
	L__to=Lthis.a2o;
	L__t=Lthis.a2;
	L__end_cap_$pi$poptgepsqueezed=Lthis.a3;
	tmp4o=L__end_cap_$pi$poptgepsqueezed.a0o;
	tmp4=L__end_cap_$pi$poptgepsqueezed.a0;
	if(L__t===tmp4&&L__to===tmp4o){
		tmp4o=Lthis.a1o;
		tmp4=Lthis.a1;
		L$ppre=Lthis.a0;
		if(tmp4o>0){
			Lsub$pptr$plhs$pcast=(Math.imul(tmp4o,4));
			Lsub$pptr$psub=Lsub$pptr$plhs$pcast-(Math.imul(0,4))|0;
			Lidx$pneg=((Lsub$pptr$psub>>2)+1|0)/-2|0;
			Lsub$pptr$psub$pi$pi=(Math.imul(L__to,4))-Lsub$pptr$plhs$pcast|0;
			Lsub$pptr$pdiv$pi$pi=Lsub$pptr$psub$pi$pi>>2;
			if((Lsub$pptr$pdiv$pi$pi|0)!==0){
				Lsub$pptr$psub$pi$pi>>>=2;
				if((Lsub$pptr$psub$pi$pi|0)!==0){
					Lsub$pptr$plhs$pcast=Lidx$pneg+Lsub$pptr$psub$pi$pi|0;
					if((Lsub$pptr$psub|0)>-12){
						Lsub$pptr$psub=Lidx$pneg;
						Lsub$pptr$psub$pi$pi=0;
						while(1){
							L$ppre=tmp4[tmp4o+Lsub$pptr$psub$pi$pi|0];
							tmp4[tmp4o+Lsub$pptr$psub|0]=L$ppre;
							Lsub$pptr$psub=Lsub$pptr$psub+1|0;
							if(tmp4!==tmp4||(tmp4o+Lsub$pptr$plhs$pcast|0)!==(tmp4o+Lsub$pptr$psub|0)){
								Lsub$pptr$psub$pi$pi=Lsub$pptr$psub$pi$pi+1|0;
								continue;
							}
							break;
						}
					}else while(1){
						Lsub$pptr$psub$pi$pi=Lsub$pptr$psub$pi$pi-1|0;
						Lsub$pptr$plhs$pcast=Lsub$pptr$plhs$pcast-1|0;
						L$ppre=tmp4[tmp4o+Lsub$pptr$psub$pi$pi|0];
						tmp4[tmp4o+Lsub$pptr$plhs$pcast|0]=L$ppre;
						if(tmp4!==tmp4||(tmp4o+Lidx$pneg|0)!==(tmp4o+Lsub$pptr$plhs$pcast|0))continue;
						break;
					}
				}
				L$ppreo=Lthis.a1o;
				L$ppre=Lthis.a1;
			}else{
				L$ppreo=tmp4o;
				L$ppre=tmp4;
			}
			Lthis.a2=tmp4;
			Lthis.a2o=(tmp4o+Lidx$pneg|0)+Lsub$pptr$pdiv$pi$pi|0;
			Lthis.a1=L$ppre;
			Lthis.a1o=L$ppreo+Lidx$pneg|0;
			L__to=(tmp4o+Lidx$pneg|0)+Lsub$pptr$pdiv$pi$pi|0;
			L__t=tmp4;
		}else{
			Lsub$pptr$psub=(Math.imul(L__to,4))-(Math.imul(0,4))>>1;
			Lsub$pptr$psub=(Lsub$pptr$psub|0)!==0?Lsub$pptr$psub|0:1|0;
			L__t={a0:nullArray,a1:nullArray,a1o:0,a2:nullArray,a2o:0,a3:{a0:nullArray,a0o:0,a1:null}};
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(L__t,Lsub$pptr$psub,Lsub$pptr$psub>>>2,L__end_cap_$pi$poptgepsqueezed);
			tmp4o=Lthis.a1o;
			tmp4=Lthis.a1;
			L$ppreo=Lthis.a2o;
			L$ppre=Lthis.a2;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(L__t,tmp4,tmp4o,L$ppre,L$ppreo);
			tmp4=Lthis.a0;
			L$ppre=L__t.a0;
			Lthis.a0=L$ppre;
			L__t.a0=tmp4;
			tmp4o=Lthis.a1o;
			tmp4=Lthis.a1;
			L$ppreo=L__t.a1o;
			L$ppre=L__t.a1;
			Lthis.a1=L$ppre;
			Lthis.a1o=L$ppreo;
			L__t.a1=tmp4;
			L__t.a1o=tmp4o;
			tmp4o=Lthis.a2o;
			tmp4=Lthis.a2;
			L$ppreo=L__t.a2o;
			L$ppre=L__t.a2;
			Lthis.a2=L$ppre;
			Lthis.a2o=L$ppreo;
			L__t.a2=tmp4;
			L__t.a2o=tmp4o;
			tmp4o=L__end_cap_$pi$poptgepsqueezed.a0o;
			tmp4=L__end_cap_$pi$poptgepsqueezed.a0;
			L$ppreo=L__t.a3.a0o;
			L$ppre=L__t.a3.a0;
			L__end_cap_$pi$poptgepsqueezed.a0=L$ppre;
			L__end_cap_$pi$poptgepsqueezed.a0o=L$ppreo;
			L__t.a3.a0=tmp4;
			L__t.a3.a0o=tmp4o;
			__ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(L__t);
			L__to=Lthis.a2o;
			L__t=Lthis.a2;
		}
	}
	L__end_cap_$pi$poptgepsqueezed=L__x[M__x];
	L__t[L__to]=L__end_cap_$pi$poptgepsqueezed;
	L__to=Lthis.a2o;
	L__t=Lthis.a2;
	Lthis.a2=L__t;
	Lthis.a2o=L__to+1|0;
}
function __ZNSt14__split_bufferIP6BubbleRSaIS1_EED2Ev(Lthis){
	var tmp0=null,tmp0o=0,tmp1=null,tmp1o=0;
	tmp0o=Lthis.a1o;
	tmp0=Lthis.a1;
	tmp1o=Lthis.a2o;
	tmp1=Lthis.a2;
	if(tmp0!==tmp1||tmp0o!==tmp1o){
		Lthis.a2=tmp1;
		Lthis.a2o=tmp1o+(((Math.imul(tmp1o,4))-(Math.imul(tmp0o,4))|0)-4>>>2^ -1)|0;
	}
}
function __ZNSt14__split_bufferIP6BubbleRSaIS1_EE18__construct_at_endISt13move_iteratorIPS1_EEENSt9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeESA_SA_(Lthis,L__first$p0,M__first$p0,L__last$p0,M__last$p0){
	var tmp0=null,L$ppre=null,L$ppreo=0,Lgeptoindexphi=0;
	if(L__first$p0!==L__last$p0||M__first$p0!==M__last$p0){
		L$ppreo=Lthis.a2o;
		L$ppre=Lthis.a2;
		Lgeptoindexphi=0;
		while(1){
			tmp0=L__first$p0[M__first$p0+Lgeptoindexphi|0];
			L$ppre[L$ppreo]=tmp0;
			L$ppreo=Lthis.a2o;
			L$ppre=Lthis.a2;
			Lthis.a2=L$ppre;
			Lthis.a2o=L$ppreo+1|0;
			Lgeptoindexphi=Lgeptoindexphi+1|0;
			if(L__first$p0!==L__last$p0||(M__first$p0+Lgeptoindexphi|0)!==M__last$p0){
				L$ppreo=L$ppreo+1|0;
				L$ppre=L$ppre;
				continue;
			}
			break;
		}
	}
}
function __ZNSt14__split_bufferIP6BubbleRSaIS1_EEC2EjjS3_(Lthis,L__cap,L__start,L__a){
	var tmp0=null,Lcond=null;
	tmp0=Lthis.a3;
	tmp0.a0=nullArray;
	tmp0.a0o=0;
	tmp0.a1=L__a;
	if((L__cap|0)!==0){
		Lcond=createPointerArray([],0,(L__cap<<2)/4|0,null);
	}else{
		Lcond=nullArray;
	}
	Lthis.a0=Lcond;
	Lthis.a2=Lcond;
	Lthis.a2o=0+L__start|0;
	Lthis.a1=Lcond;
	Lthis.a1o=0+L__start|0;
	tmp0.a0=Lcond;
	tmp0.a0o=0+L__cap|0;
}
function __ZN15BubbleContainerC1EPN6client9SquareDivE(Lthis,Lcontainer){
	Lthis.a0=Lcontainer;
	Lthis.a1=null;
	_srand();
}
function _srand(){
	var L$poptgep9$poptgep$poptgepsqueezed=null,L$poptgep$poptgep$poptgepsqueezed=null;
	L$poptgep9$poptgep$poptgepsqueezed=_impure_data.a14;
	if(L$poptgep9$poptgep$poptgepsqueezed===null){
		L$poptgep9$poptgep$poptgepsqueezed={a0:new Uint16Array(6),i1:0,a2:new Int32Array(2)};
		_impure_data.a14=L$poptgep9$poptgep$poptgepsqueezed;
		L$poptgep$poptgep$poptgepsqueezed=L$poptgep9$poptgep$poptgepsqueezed.a0;
		L$poptgep$poptgep$poptgepsqueezed[0]=13070;
		L$poptgep$poptgep$poptgepsqueezed[1]=43981;
		L$poptgep$poptgep$poptgepsqueezed[2]=4660;
		L$poptgep$poptgep$poptgepsqueezed[3]=58989;
		L$poptgep$poptgep$poptgepsqueezed[4]=57068;
		L$poptgep$poptgep$poptgepsqueezed[5]=5;
		L$poptgep9$poptgep$poptgepsqueezed.i1=11;
		L$poptgep$poptgep$poptgepsqueezed=L$poptgep9$poptgep$poptgepsqueezed.a2;
		L$poptgep$poptgep$poptgepsqueezed[1]=0;
		L$poptgep$poptgep$poptgepsqueezed[0]=1;
	}
	L$poptgep9$poptgep$poptgepsqueezed=L$poptgep9$poptgep$poptgepsqueezed.a2;
	L$poptgep9$poptgep$poptgepsqueezed[1]=0;
	L$poptgep9$poptgep$poptgepsqueezed[0]=34;
}
var _$pstr$p9=new Uint8Array([37,0]);
var _$pstr=new Uint8Array([100,105,118,0]);
var _$pstr$p1=new Uint8Array([49,48,48,37,0]);
var _$pstr$p2=new Uint8Array([97,117,116,111,0]);
var _$pstr$p3=new Uint8Array([119,104,105,116,101,0]);
var _$pstr$p4=new Uint8Array([104,105,100,100,101,110,0]);
var _$pstr$p5=new Uint8Array([97,98,115,111,108,117,116,101,0]);
var _$pstr$p6=new Uint8Array([53,48,37,0]);
var _$pstr$p7=new Uint8Array([99,101,110,116,101,114,0]);
var _$pstr$p8=new Uint8Array([102,108,101,120,0]);
var ___sf_fake_stdin=new constructor_struct$p_Z7__sFILE();
var ___sf_fake_stdout=new constructor_struct$p_Z7__sFILE();
var ___sf_fake_stderr=new constructor_struct$p_Z7__sFILE();
var _$pstr$p18$p109=new Uint8Array([67,0]);
var _promotedMalloc$p3=new constructor_struct$p_Z11_misc_reent();
var _impure_data={i0:0,a1:___sf_fake_stdin,a2:___sf_fake_stdout,a3:___sf_fake_stderr,i4:0,a5:null,i6:0,i7:0,a8:_$pstr$p18$p109[0],a9:null,a10:null,i11:0,i12:0,a13:null,a14:null,a15:null,a16:null,a17:null,a18:null,a19:{a0:null,i1:0,a2:createPointerArray([],0,32,null),a3:null},a20:{a0:null,i1:0,a2:null},a21:null,a22:_promotedMalloc$p3,a23:null};
function constructor_struct$p_Z7__sFILE(){
	this.a0=null;
	this.i1=0;
	this.i2=0;
	this.i3=0;
	this.a4={a0:null,i1:0};
	this.i5=0;
	this.a6=null;
	this.a7=null;
	this.a8=null;
	this.a9=null;
	this.a10=null;
	this.a11=null;
	this.a12={a0:null,i1:0};
	this.a13=null;
	this.i14=0;
	this.a15=new Uint8Array(4);
	this.a16={a0:null,i1:0};
	this.i17=0;
	this.i18=0;
	this.i19=0;
	this.a20={i0:0,i1:0};
	this.i21=0;
}
function constructor_struct$p_Z6_reent(){
	this.i0=0;
	this.a1=null;
	this.a2=null;
	this.a3=null;
	this.i4=0;
	this.a5=null;
	this.i6=0;
	this.i7=0;
	this.a8=null;
	this.a9=null;
	this.a10=null;
	this.i11=0;
	this.i12=0;
	this.a13=null;
	this.a14=null;
	this.a15=null;
	this.a16=null;
	this.a17=null;
	this.a18=null;
	this.a19={a0:null,i1:0,a2:createPointerArray([],0,32,null),a3:null};
	this.a20={a0:null,i1:0,a2:null};
	this.a21=null;
	this.a22=null;
	this.a23=null;
}
function constructor_struct$p_Z11_misc_reent(){
	this.a0=null;
	this.a1={i0:0,i1:0};
	this.a2={i0:0,i1:0};
	this.a3={i0:0,i1:0};
	this.a4=new Uint8Array(8);
	this.i5=0;
	this.a6={i0:0,i1:0};
	this.a7={i0:0,i1:0};
	this.a8={i0:0,i1:0};
	this.a9={i0:0,i1:0};
	this.a10={i0:0,i1:0};
}
function createArray_class$p_Z6Bubble(e){
	var r=[];
	for(var i=0;i<e;i++)
	r[i]={d0:-0.,a1:[-0.],a2:null,a3:null,i4:0,a5:[-0.]};
	return r;
}
function createArray_literal1(e){
	var r=[];
	for(var i=0;i<e;i++)
	r[i]=-0.;
	return r;
}
function createPointerArray(r,s,e,v){for(var i=s;i<e;i++)r[i]=v;return r;}
function BubbleContainer(a0){
	this.a0=null;
	this.a1=null;
	;
	this.d=[this];
	if (arguments.length===1&&arguments[0]===undefined){
		return;
	}
	__ZN15BubbleContainerC1EPN6client9SquareDivE(this,a0);
}
BubbleContainer.prototype.insert=function (a0){
	return __ZN15BubbleContainer6insertEPN6client11HTMLElementE(this,a0);
};
BubbleContainer.prototype.erase=function (a0){
	return __ZN15BubbleContainer5eraseEPN6client11HTMLElementE(this,a0);
};
BubbleContainer.prototype.doStep=function (){
	return __ZN15BubbleContainer6doStepEv(this);
};
BubbleContainer.promise=
Promise.resolve();

export default BubbleContainer;
